version: '3.4'

services:
  skillup.postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres
    env_file:
      - .env
    shm_size: '4gb'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - ${POSTGRES_PORT}:5432

  skillup.smtpserver:
    container_name: ${SMTP__HOST}
    image: changemakerstudiosus/papercut-smtp:latest
    env_file:
      - .env
    ports:
     - ${SMTP_HTTP_PORT}:80
     - ${SMTP__PORT}:25

  skillup.bootstrapper:
    container_name: skillup-api
    image: ${DOCKER_REGISTRY-}skillupbootstrapper
    env_file:
      - .env
    build:
      context: .
      dockerfile: Bootstrapper/Skillup.Bootstrapper/Dockerfile
    depends_on:
      - skillup.postgres
      - skillup.smtpserver

volumes:
  postgres:
    driver: local