services:
  skillup.postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres
    env_file:
      - .env
    shm_size: '4gb'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - ${POSTGRES_PORT}:5432

  skillup.rabbitmq:
    container_name: ${RABBITMQ_HOST}    
    image: rabbitmq:3-management-alpine
    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
        - ${RABBITMQ_PORT}:5672
        - ${RABBITMQ_HTTP_PORT}:15672

  skillup.bootstrapper:
    container_name: skillup-api
    image: ${DOCKER_REGISTRY-}skillupbootstrapper
    env_file:
      - .env
    build:
      context: .
      dockerfile: Bootstrapper/Skillup.Bootstrapper/Dockerfile
    depends_on:
      - skillup.postgres
      - skillup.rabbitmq
  
  skillup.nginx:
    container_name: skillup-nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - skillup.bootstrapper    
    ports:
      - "4000:4000"